# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Unit and Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    
    - name: Get mock-api source code
      run: |
        git clone https://github.com/adeviney/mock-api-weather.git
        cd mock-api-weather
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dotenv
      run: npm install dotenv --save
      
    - name: Create .env file
      run: |
          pwd
          touch .env
          echo API_KEY = ${{ secrets.API_KEY }} >> .env
          cat .env
      
    - name: Run Mock Server in background
      run: node app.js &
    
    - name: Swift Build
      run: |
        cd ..
        pwd
        swift build -v
        

    - name: Swift Run tests
      run: swift test -v
    
