# This workflow builds and tests the Swift package.
# To fulfill the dependency on the mock server, it clones the code from that repo, sets up node.js environment,
#   and runs the mock-server in the background to communicate with the Swift tests
# API key secrets are handled with Github repository secret feature.

name: Swift Build and Test (Unit and Integration with API server)

on:
  push:
    branches: [ "main"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Get mock-api source code
      run: |
        git clone https://github.com/adeviney/mock-api-weather.git
    
    - name: Install Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dotenv
      working-directory: ./mock-api-weather
      run: npm install dotenv --save
      
    - name: Create .env file
      working-directory: ./mock-api-weather
      run: |
          pwd
          touch .env
          echo API_KEY = ${{ secrets.API_KEY }} >> .env
          cat .env
      
    - name: Run Mock Server in background
      working-directory: ./mock-api-weather
      run: node app.js &
    
    - name: Swift Build
      working-directory: ./MyLibrary
      run: swift build -v
        

    - name: Swift Run tests
      working-directory: ./MyLibrary
      run: |
        export API_KEY=${{ secrets.API_KEY }}
        swift test -v
    
    
